version: '3.9'

services:
  db:
    image: postgres:1
    environment:
      POSTGRES_USER: ((POSTGRES_USER))
      POSTGRES_PASSWORD: ((POSTGRES_PASSWORD))
      POSTGRES_DB: ((POSTGRES_DB))
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: ((DATABASE_URL))
      EMAIL_USER: ((EMAIL_USER))
      EMAIL_PASS: ((EMAIL_PASS))
      NOTIFY_EMAIL: ((NOTIFY_EMAIL))
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run start

volumes:
  postgres_data: